#ifndef __PAGETABLE_PORT_H__
#define __PAGETABLE_PORT_H__

#include "asm/pagetable_hwdef.h"

/*
 * Software defined PTE bits definition.
 */
#define PTE_VALID		(1UL << 0)
#define PTE_WRITE		(PTE_DBM)		    /* same as DBM (51) */
#define PTE_DIRTY		(1UL << 55)
#define PTE_SPECIAL		(1UL << 56)
#define PTE_PROT_NONE   (1UL << 58)         /* only when !PTE_VALID */

#define PROT_DEFAULT        (PTE_TYPE_PAGE | PTE_AF | PTE_SHARED)

#define PROT_DEVICE_nGnRnE	(PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_DEVICE_nGnRnE_IDX))
#define PROT_DEVICE_nGnRE	(PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_DEVICE_nGnRE_IDX))
#define PROT_NORMAL_NC		(PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_NORMAL_NC_IDX))
#define PROT_NORMAL_WT		(PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_NORMAL_WT_IDX))
#define PROT_NORMAL         (PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_NORMAL_IDX))

#define PMD_PROT_DEFAULT        (PMD_TYPE_SECT | PMD_SECT_AF | PMD_SECT_S)
#define PMD_PROT_DEVICE_nGnRnE  (PMD_PROT_DEFAULT | PMD_SECT_PXN | PMD_SECT_UXN | PMD_ATTRINDX(MT_DEVICE_nGnRnE_IDX))
#define PMD_PROT_NORMAL         (PMD_PROT_DEFAULT | PMD_SECT_PXN | PMD_SECT_UXN | PMD_ATTRINDX(MT_NORMAL_IDX))

#define PAGE_KERNEL         PROT_NORMAL
#define PAGE_KERNEL_DEVICE  PROT_DEVICE_nGnRnE
#define PMD_KERNEL          PMD_PROT_NORMAL
#define PMD_KERNEL_DEVICE   PMD_PROT_DEVICE_nGnRnE

#define PAGE_KERNEL_RO		((PAGE_KERNEL & (~PTE_WRITE)) | PTE_RDONLY)
#define PAGE_KERNEL_ROX		((PAGE_KERNEL & ~(PTE_WRITE | PTE_PXN)) | PTE_RDONLY)
#define PAGE_KERNEL_EXEC	(PAGE_KERNEL & (~PTE_PXN))

#endif
