#ifndef __PAGETABLE_PORT_H__
#define __PAGETABLE_PORT_H__

#include "asm/pagetable_hwdef.h"

/*
 * Software defined PTE bits definition.
 */
#define PTE_VALID		(1UL << 0)
#define PTE_WRITE		(PTE_DBM)		    /* same as DBM (51) */
#define PTE_DIRTY		(1UL << 55)
#define PTE_SPECIAL		(1UL << 56)
#define PTE_PROT_NONE   (1UL << 58)         /* only when !PTE_VALID */

#define PROT_DEFAULT        (PTE_TYPE_PAGE | PTE_AF | PTE_SHARED)

#define PROT_DEVICE_nGnRnE	(PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_DEVICE_nGnRnE))
#define PROT_DEVICE_nGnRE	(PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_DEVICE_nGnRE))
#define PROT_NORMAL_NC		(PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_NORMAL_NC))
#define PROT_NORMAL_WT		(PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_NORMAL_WT))
#define PROT_NORMAL         (PROT_DEFAULT | PTE_PXN | PTE_UXN | PTE_DIRTY | PTE_WRITE | PTE_ATTRINDX(MT_NORMAL))

#define PAGE_KERNEL         PROT_NORMAL

#define PAGE_KERNEL_RO		((PAGE_KERNEL & (~PTE_WRITE)) | PTE_RDONLY)
#define PAGE_KERNEL_ROX		((PAGE_KERNEL & ~(PTE_WRITE | PTE_PXN)) | PTE_RDONLY)
#define PAGE_KERNEL_EXEC	(PAGE_KERNEL & (~PTE_PXN))

#endif
