#ifndef STUPIDOS_BUSYBOX_SHIM_H
#define STUPIDOS_BUSYBOX_SHIM_H

/*
 * BusyBox ash / lineedit 专用的最小配置层。
 *
 * 这里不再接 upstream BusyBox 的完整头文件树，而是直接接入
 * stupidos 自己的兼容层。这样可以避免和我们自己的 FILE / stdio
 * 实现互相打架，同时保留 BusyBox 源码的大部分原始逻辑。
 */

#include "libbb.h"

#define ENABLE_SHELL_ASH 1
#define ENABLE_SHELL_HUSH 0
#define IF_SHELL_ASH(...) __VA_ARGS__
#define IF_SHELL_HUSH(...)

#define ENABLE_FEATURE_SH_STANDALONE 0
#define ENABLE_FEATURE_SH_NOFORK 0
#define ENABLE_FEATURE_PREFER_APPLETS 0
#define ENABLE_FEATURE_SH_EMBEDDED_SCRIPTS 0
#define ENABLE_FEATURE_INSTALLER 0

#define ENABLE_FEATURE_EDITING 1
#define ENABLE_FEATURE_EDITING_VI 0
#define ENABLE_FEATURE_EDITING_FANCY_PROMPT 0
#define ENABLE_FEATURE_TAB_COMPLETION 0
#define ENABLE_FEATURE_USERNAME_COMPLETION 0
#define ENABLE_FEATURE_EDITING_WINCH 0
#define ENABLE_FEATURE_EDITING_ASK_TERMINAL 0
#define ENABLE_FEATURE_EDITING_SAVEHISTORY 0
#define ENABLE_FEATURE_EDITING_SAVE_ON_EXIT 0

#define CONFIG_FEATURE_EDITING_MAX_LEN 1024
#define CONFIG_FEATURE_EDITING_HISTORY 16

#define ENABLE_UNICODE_SUPPORT 0
#define ENABLE_UNICODE_USING_LOCALE 0
#define ENABLE_UNICODE_PRESERVE_BROKEN 0
#define ENABLE_UNICODE_BIDI_SUPPORT 0

#define ENABLE_ASH_OPTIMIZE_FOR_SIZE 1
#define ENABLE_ASH_INTERNAL_GLOB 1
#define ENABLE_ASH_BASH_COMPAT 0
#define ENABLE_ASH_JOB_CONTROL 0
#define ENABLE_ASH_ALIAS 0
#define ENABLE_ASH_RANDOM_SUPPORT 0
#define ENABLE_ASH_EXPAND_PRMT 0
#define ENABLE_ASH_IDLE_TIMEOUT 0
#define ENABLE_ASH_MAIL 0
#define ENABLE_ASH_ECHO 1
#define ENABLE_ASH_PRINTF 1
#define ENABLE_ASH_TEST 1
#define ENABLE_ASH_HELP 0
#define ENABLE_ASH_GETOPTS 1
#define ENABLE_ASH_CMDCMD 0
#define ENABLE_ASH_BASH_SOURCE_CURDIR 0
#define ENABLE_ASH_BASH_NOT_FOUND_HOOK 0

#define IF_ASH_BASH_COMPAT(...)
#define IF_ASH_JOB_CONTROL(...)
#define IF_ASH_ALIAS(...)
#define IF_ASH_RANDOM_SUPPORT(...)
#define IF_ASH_EXPAND_PRMT(...)
#define IF_ASH_IDLE_TIMEOUT(...)
#define IF_ASH_MAIL(...)
#define IF_ASH_ECHO(...) __VA_ARGS__
#define IF_ASH_PRINTF(...) __VA_ARGS__
#define IF_ASH_TEST(...) __VA_ARGS__
#define IF_ASH_HELP(...)
#define IF_ASH_GETOPTS(...) __VA_ARGS__
#define IF_ASH_CMDCMD(...)
#define IF_ASH_BASH_SOURCE_CURDIR(...)
#define IF_ASH_BASH_NOT_FOUND_HOOK(...)

#define IF_FEATURE_EDITING_VI(...)
#define IF_FEATURE_EDITING_FANCY_PROMPT(...)
#define IF_FEATURE_TAB_COMPLETION(...)
#define IF_FEATURE_USERNAME_COMPLETION(...)
#define IF_FEATURE_EDITING_WINCH(...)
#define IF_FEATURE_EDITING_ASK_TERMINAL(...)

/*
 * BusyBox 头文件里常见的属性和可见性宏，按最小需要补上。
 */
#ifndef UNUSED_PARAM
# define UNUSED_PARAM __attribute__((unused))
#endif
#ifndef NORETURN
# define NORETURN __attribute__((noreturn))
#endif
#ifndef RETURNS_MALLOC
# define RETURNS_MALLOC __attribute__((malloc))
#endif
#ifndef PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN
# define PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN
#endif
#ifndef POP_SAVED_FUNCTION_VISIBILITY
# define POP_SAVED_FUNCTION_VISIBILITY
#endif

#endif
